import Head from "next/head";
import { Header } from "@/components";

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/site-logo.svg" type="image/x-icon" />
      </Head>
      <Header />
      <main>
        {/* {Hero} */}
        <section>
          {/* {Row} */}
          {/* {Big Row} */}
          {/* {Row} */}
          {/* {BigRow} */}
        </section>
      </main>
    </div>
  );
}
