import Head from "next/head";
import { Header, Hero } from "@/components";
import axios from "axios";
import { API_REQUSET } from "@/service/api.service";
import { useEffect } from "react";
import { GetServerSideProps } from "next";
import { IMovie } from "@/interfaces/app.interface";

export default function Home({ dataProps }: IHomeProps): JSX.Element {
  return (
    <div className="flex flex-col min-h-screen ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/site-logo.svg" type="image/x-icon" />
      </Head>
      <Header />
      <main className="relative top-[70px] md:top-[100px]  h-[85vh]  overflow-hidden">
        <Hero data={dataProps} />
        <section>
          {/* {Row} */}
          {/* {Big Row} */}
          {/* {Row} */}
          {/* {BigRow} */}
        </section>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<IHomeProps> = async () => {
  const trending = await fetch(API_REQUSET.trending).then((res) => res.json());

  return {
    props: { dataProps: trending.results },
  };
};

interface IHomeProps {
  dataProps: IMovie[];
}
