import Head from "next/head";
import { Header, Hero, Row } from "@/components";

import { API_REQUSET } from "@/service/api.service";
import { useEffect } from "react";
import { GetServerSideProps } from "next";
import { IMovie } from "@/interfaces/app.interface";

export default function Home({ dataProps, topRated }: IHomeProps): JSX.Element {
  return (
    <div className="flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/site-logo.svg" type="image/x-icon" />
      </Head>
      <Header />
      <main className="relative flex flex-col top-[70px] md:top-[100px]  h-screen  ">
        <Hero data={dataProps} />
        <section className="flex flex-col w-full">
          <Row data={topRated} title="Top Rated" />
          {/* {Big Row} */}
          {/* {Row} */}
          {/* {BigRow} */}
        </section>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<IHomeProps> = async () => {
  const trending = await fetch(API_REQUSET.trending).then((res) => res.json());
  const topRatedData = await fetch(API_REQUSET.top_rated).then((res) =>
    res.json()
  );
  return {
    props: { dataProps: trending.results, topRated: topRatedData.results },
  };
};

interface IHomeProps {
  dataProps: IMovie[];
  topRated: IMovie[];
}
